// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euhthwosspivtzmqifsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1aHRod29zc3BpdnR6bXFpZnN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyODEwOTQsImV4cCI6MjA2Njg1NzA5NH0.4ujSylcarIntWfgtwuppMKm6zHkGm9VgrQGqakLz3KI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});